name: Kano-Live-Record
on:
  watch:
    types: started
  workflow_dispatch:
jobs:
  Kano-Live-Record:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: 加载代码
        uses: actions/checkout@main
      - name: 设置时区
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: 'Asia/Shanghai'
          timezoneMacos: 'Asia/Shanghai'
          timezoneWindows: 'Asia/Shanghai'
      - name: 环境搭建
        run: |
          sudo snap install ffmpeg --channel=latest/edge
          pip3 install setuptools
          pip3 install streamlink
          pip3 install jsonpath
          chmod 777 ./OneDriveUploader
      - name: 运行录制脚本
        env:
          ONEDRIVE_REFRESH_TOKEN: ${{ secrets.ONEDRIVE_REFRESH_TOKEN }}
          QSMG_TOKEN: ${{ secrets.QSMG_TOKEN }}
          TWITCH_HEADERS: ${{ secrets.TWITCH_HEADERS }}
        run: |
          export PATH=/home/runner/.local/bin:$PATH
          python3 kano_live_record.py
